### ISSUE TITLE
Node Error

### ISSUE THREAD

**Issue by rayhanbone** [muink/luci-app-homeproxy#1]
if add node,
error:
TypeError
Cannot convert undefined or null to object

**Comment by muink** [comment]
Please provide more details and reproduction steps
A screenshot would be better

**Comment by rayhanbone** [comment]
> Please provide more details and reproduction steps A screenshot would be better

Error if add node

**Comment by muink** [comment]
Mitigation measures: Add any subscription and save it
![image](https://github.com/muink/luci-app-homeproxy/assets/7929014/74aeb4d1-9427-467e-8191-9a80bb78ca28)

I will submit a patch later

**Comment by muink** [comment]
Fixed
