### ISSUE TITLE
规则集页面报错

### ISSUE THREAD

**Issue by kenzo-tm** [muink/luci-app-homeproxy#13]
![image](https://github.com/user-attachments/assets/ceb34aed-1294-4061-942e-59d5b7c93bde)

规则集页面报错，不知道是固件的问题还是包的问题。
固件用的 immortalwrt 的 master 分支。

**Comment by kenzo-tm** [comment]
![image](https://github.com/user-attachments/assets/ddd8595f-507d-4f47-88dc-1958eb6bda5a)
![image](https://github.com/user-attachments/assets/90f45a40-8c5d-4214-8096-2ffd3824d101)

hp.handleAdd 是 undefined

**Comment by muink** [comment]
<img width="165" alt="image" src="https://github.com/user-attachments/assets/f11488c3-5076-410f-af44-06483f1fcda6">
<img width="975" alt="image" src="https://github.com/user-attachments/assets/9b3fced4-40c9-43b2-829a-650a061275f6">
无法重现错误
