### ISSUE TITLE
请教，ruleset 用的是 remote 方式，如何手动更新

### ISSUE THREAD

**Issue by imken** [muink/luci-app-homeproxy#15]
在 ruleset setting 中建立自己维护的的ruleset，模式是remote 远程文件， 时不时会添修改内容。

在 ruleset 中只有“更新间隔” 可以设置，有没有方法可以手动刷新呢？

**Comment by muink** [comment]
没有一键式的的方法，你可以把更新时间改成1s
然后等服务重启后等个几秒，再把时间改回来

**Comment by imken** [comment]
> 没有一键式的的方法，你可以把更新时间改成1s 然后等服务重启后等个几秒，再把时间改回来

我就是这样干的，哈哈，希望以后有个手动更新的按钮。

**Comment by muink** [comment]
sing-boc似乎没有暴露这样的接口
