### ISSUE TITLE
没有Selector和URLTest

### ISSUE THREAD

**Issue by jinhill** [muink/luci-app-homeproxy#19]
我刚刚下载了dev/main分支，编译安装后节点类型没有Selector和URLTest，
安装报错：
opkg install luci-app-homeproxy_git-24.239.33072-5a3c88d_all.ipk
Installing luci-app-homeproxy (git-24.239.33072-5a3c88d) to root...
Configuring luci-app-homeproxy.
//usr/lib/opkg/info/luci-app-homeproxy.postinst: /etc/uci-defaults/luci-homeproxy-migration: line 29: pushd: not found
//usr/lib/opkg/info/luci-app-homeproxy.postinst: /etc/uci-defaults/luci-homeproxy-migration: line 35: popd: not found
opkg install luci-i18n-homeproxy-zh-cn_git-24.226.23824-9a48dd3_all.ipk
Installing luci-i18n-homeproxy-zh-cn (git-24.226.23824-9a48dd3) to root...
Configuring luci-i18n-homeproxy-zh-cn.
//usr/lib/opkg/info/luci-i18n-homeproxy-zh-cn.postinst: .: line 2: can't open '/etc/uci-defaults/luci-i18n-homeproxy-zh-cn': No such file or directory

**Comment by muink** [comment]
依赖问题, 装个 bash 就好了
另外这个仓库是开发分支, 不是稳定分支, 有时候会有些 bug 的

**Comment by jinhill** [comment]
@muink 感谢解答，如果脚本兼容POSIX sh,这样默认openwrt环境就可以支持。
