### ISSUE TITLE
节点设置页面是不是配错了文件？

### ISSUE THREAD

**Issue by ash0080** [muink/luci-app-homeproxy#21]
<img width="466" alt="Arc_z9JZtO2vqq" src="https://github.com/user-attachments/assets/7dd79e02-2f42-4250-b34a-2b98eda29218">
<img width="672" alt="Arc_juH28DBaIf" src="https://github.com/user-attachments/assets/0bdf85e8-710c-49cd-91d8-118443c98d29">
不好意思 打扰了  请问这个节点配置页面这样对么  似乎配的是古早homeproxy的添加单节点的view
这样似乎没法做proxygroup？？ 
还有个问题， 现在clash dashboard 被拿掉了么？ 找不到按钮  还是说 必须运行+有ruleset同时生效才会显示出来？

**Comment by muink** [comment]
这个是节点设置页面不是 ruleset 页面
dashboard 只在自定义路由模式下有效

**Comment by ash0080** [comment]
> 这个是节点设置页面不是 ruleset 页面 dashboard 只在自定义路由模式下有效
我不是指ruleset页面有问题哈, 而是proxygroup界面不对, 就是设置selector/urltest之类的界面, 我看别人的截图24.226, 跟现在我截图的这个截然不同

**Comment by ash0080** [comment]
> 这个是节点设置页面不是 ruleset 页面 dashboard 只在自定义路由模式下有效

不是ruleset页面, 是在说proxygroup界面(就是节点设置里的第一个tab), 也就是应该来设置selector/urltest之类的界面, 而这个界面现在是我截图的这个样子, 我看别人的截图24.226, 跟现在的截图截然不同,是正常的

**Comment by ash0080** [comment]
补充一点,现在即使我手写配置文件,载入到界面里, 比如 "香港节点selector", 点击编辑打开仍然是截图这样的表单

**Comment by muink** [comment]
建议清除页面缓存
或使用无痕页面在尝试

**Comment by ash0080** [comment]
> 建议清除页面缓存 或使用无痕页面在尝试

确实是缓存的问题，刷新后正常了，谢谢你的解答
