### ISSUE TITLE
反复测试了这个问题如何解决？

### ISSUE THREAD

**Issue by onlyfirer** [muink/luci-app-homeproxy#4]
同一个节点科学，如果默认DNS是远程DNS就会被墙的，换成默认为国内的DNS就可以出去，但是测试DNS泄漏的时候就有国内的DNS
但也有一种节点，不管默认DNS是远程DNS还是国内的DNS，他都可以出去。当然用默认国内DNS的话测试dns泄漏时也是有内的DNS
如下图：
![1-2](https://github.com/muink/luci-app-homeproxy/assets/94467799/4b93fcc5-af86-49ec-91a8-72e3b735d90b)
出站是这个：芝麻开门
![001](https://github.com/muink/luci-app-homeproxy/assets/94467799/96de16d9-a356-49a0-8942-d15af2a8f9a3)
这个是采用默认为远程的，那么接到YY相关的节点都出不去。然后free 开头的节点可以出去，
![001](https://github.com/muink/luci-app-homeproxy/assets/94467799/6de168c8-bff2-4a76-8556-0d6db572324f)

两个不同机场的节点。但是只有我在芝麻开门这里选择了free节点后，但youtube选的是YY 的节点同样可以科学了。
只要在芝麻开门这个地方换成YY的节点就全部出不去了，包括国内（这里没有绕过国内的设置）也不能上网了。
第二种形式：
![2](https://github.com/muink/luci-app-homeproxy/assets/94467799/e63ff2bb-57fb-4e04-a192-d737b5870e65)
把默认的改成国内的就都 可以科学了，在芝麻开门这里也不一定要选free节点了，全部都可以科学上网，但是就是DNS检测时有国内的
这是什么原因造成的？
有没有办法解决？

**Comment by muink** [comment]
请发去除了隐私信息的config文件 `/etc/config/homeproxy`

**Comment by onlyfirer** [comment]
我发配置文件放了两对不同的节点
[homeproxy.txt](https://github.com/muink/luci-app-homeproxy/files/14976819/homeproxy.txt)
测试看下是什么问题！

**Comment by onlyfirer** [comment]
上面这个配置把网卡的IPV6开启与禁止的国内访问速度延迟不一样。
第一张是开启的
![1](https://github.com/muink/luci-app-homeproxy/assets/94467799/1186b456-b049-4a75-b3b5-e288239cd5e7)
第二张是禁止IPV6网卡信息
![2](https://github.com/muink/luci-app-homeproxy/assets/94467799/8eb35fdc-b2fe-4c15-9913-7a107a855606)

**Comment by muink** [comment]
### 简单解释下原因: 
默认dns服务器 `Cloudfale` 的地址是域名, 需要解析为 ip 才能访问到. 故它首先要请求到自身的 `dns.quad9.net` 的 ip 地址才能开始工作.
所以 `dns.quad9.net` 的 dns请求经由 `Cloudfale` 这个 dns server 项设置的出站 `芝麻开门` 向外发出, 但是 yy 节点的地址也是域名而不是 ip , 同样需要进行 dns 解析为 ip , 而且大概率不匹配 `dnsrule:cn_domain` 也不匹配 `dnsrule:google_domain` , 那么就会走默认的dns服务器, 也就是 `Cloudfale`. boom陷入死循环了! 但是 free 节点是 ip 地址, 直接就能连接不需要dns解析, 所以就没有这个问题.
![Snipaste_2024-04-15_19-13-03](https://github.com/muink/luci-app-homeproxy/assets/7929014/d150d73b-3113-4f2e-becd-74ff9bf1c698)
![Snipaste_2024-04-15_19-12-22](https://github.com/muink/luci-app-homeproxy/assets/7929014/5ae5ec79-757d-40c2-a0ae-7ea9436ef244)
### 解决办法: 
这条规则加到 dns rules 最上面
![image](https://github.com/muink/luci-app-homeproxy/assets/7929014/9622cc95-08fa-418a-a49e-bb5d6eb8e166)
另外, 这两条规则, 如果你的目的是 `匹配cn ruleset走直连outbound` 和 `匹配国外 ruleset走芝麻开门outbound` 的话, 建议去掉, 因为这个是 `匹配来自指定 outbound 的 dns请求`, 而不是前面的目的
![Snipaste_2024-04-15_19-50-17](https://github.com/muink/luci-app-homeproxy/assets/7929014/3bbfe719-fd40-4b0f-97ea-42dc3016c347)
![Snipaste_2024-04-15_19-48-41](https://github.com/muink/luci-app-homeproxy/assets/7929014/8397fc6e-a03d-4fd0-ac61-bb4086273b5f)
