### ISSUE TITLE
更新订阅机场节点bug反馈

### ISSUE THREAD

**Issue by onlyfirer** [muink/luci-app-homeproxy#5]
配置文件其它都设置好的，不更新正常启动使用，但是只要更新节点，新的配置文件就启动不了homeprxoy了！

**Comment by onlyfirer** [comment]
好像是针对谋些协议的节点，并不是所有。

**Comment by muink** [comment]
协议解析问题请向上游反馈 https://github.com/immortalwrt/homeproxy
并提供错误日志

**Comment by onlyfirer** [comment]
好的
