### ISSUE TITLE
无法打开clash dashboard

### ISSUE THREAD

**Issue by 631894570** [muink/luci-app-homeproxy#7]
immortalwrt 23.05分支添加master分支编译，luci下有显示"open clash dashboard" 按钮，点击后为“192.168.10.10绝了我们的连接请求。”，/etc/homeproxy/resources目录下好像没有dashboard相关文件
![PixPin_2024-07-07_16-47-12](https://github.com/muink/luci-app-homeproxy/assets/43724996/01ac4574-87b2-4fd5-bf73-36a44a974745)

**Comment by zexry619** [comment]
how to solce this?

**Comment by 631894570** [comment]
> 如何解决这个问题？

Routing mode select "custom routing"
